spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html

#    servlet:


logging:
  level:
    root: warn
    com.pika: debug
  file:
    path: log/blog.log

server:
  port: 8080

